version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl and use pipenv to install dependencies
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install dist/convrsn-0.0.1-py3-none-any.whl
            pipenv install pytest
      - run:
          command: |  # Run test suite
            pytest
  test_pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            twine upload --repository testpypi dist/*
  pypi_publish:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout  # checkout source code to working directory
      - run:
          command: |  # create whl, install twine and publish
            python setup.py sdist bdist_wheel
            sudo pip install pipenv
            pipenv install twine
            twine upload --repository dist/*
workflows:
  build_test_publish:
    jobs:
      - build_test
      - test_pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - develop
                - master
      - pypi_publish:
          requires:
            - test_pypi_publish
          filters:
            branches:
              only:
                - master
